import { describe, expect, it } from "vitest";
import type { DirectoryCity } from "./city-directory";
import { findCitySearchMatch } from "./city-hero-search-utils";

const cities: DirectoryCity[] = [
  {
    apartmentPrice: 4200,
    averagePrice: 4300,
    departmentCode: "13",
    housePrice: 4400,
    name: "La Ciotat",
    postalCode: "13600",
    slug: "la-ciotat",
    trend: null,
  },
  {
    apartmentPrice: 4100,
    averagePrice: 4200,
    departmentCode: "13",
    housePrice: 4300,
    name: "Gémenos",
    postalCode: "13420",
    slug: "gemenos",
    trend: -0.2,
  },
];

describe("city hero search", () => {
  it("matches a city name without requiring accents", () => {
    expect(findCitySearchMatch(cities, "gemenos")?.slug).toBe("gemenos");
  });

  it("matches an available postal code", () => {
    expect(findCitySearchMatch(cities, "13600")?.slug).toBe("la-ciotat");
  });

  it("matches the value generated by the suggestion list", () => {
    expect(findCitySearchMatch(cities, "La Ciotat — 13600")?.slug).toBe("la-ciotat");
  });

  it("returns no city for an unavailable query", () => {
    expect(findCitySearchMatch(cities, "Paris")).toBeNull();
  });
});
