import { describe, expect, it } from "vitest";
import { sanitizePropertyDescription } from "./sanitize-rich-html";

describe("sanitizePropertyDescription", () => {
  it("keeps the formatting generated by the rich-text editor", () => {
    expect(sanitizePropertyDescription("<h2>Titre</h2><p>Texte <strong>important</strong></p><ul><li>Point</li></ul>"))
      .toBe("<h2>Titre</h2><p>Texte <strong>important</strong></p><ul><li>Point</li></ul>");
  });

  it("removes scripts, event handlers and unsafe elements", () => {
    const result = sanitizePropertyDescription(
      '<p onclick="alert(1)">Texte</p><script>alert(2)</script><img src=x onerror="alert(3)">',
    );

    expect(result).toBe("<p>Texte</p>");
  });
});
