import { NextResponse } from "next/server";
import { getAdminSession } from "@/lib/admin/auth";
import { adminRest, getSupabaseAdminConfig, type PropertyImage } from "@/lib/properties";
const text=(f:FormData,k:string)=>String(f.get(k)??"").trim(); const num=(f:FormData,k:string)=>text(f,k)?Number(text(f,k)):null;
export async function PATCH(request:Request,{params}:{params:Promise<{id:string}>}){
 if(!(await getAdminSession()))return NextResponse.json({error:"Non autorisé"},{status:401});
 try{const {id}=await params;const f=await request.formData();const status=text(f,"status")||"draft";const payload={title:text(f,"title"),city_name:text(f,"city_name"),status,postal_code:text(f,"postal_code")||null,neighborhood:text(f,"neighborhood")||null,property_type:text(f,"property_type")||"apartment",price:num(f,"price"),surface_m2:num(f,"surface_m2"),rooms:num(f,"rooms"),bedrooms:num(f,"bedrooms"),floor_label:text(f,"floor_label")||null,short_description:text(f,"short_description")||null,description:text(f,"description")||null,address:text(f,"address")||null,energy_rating:text(f,"energy_rating")||null,condominium_charges_monthly:num(f,"condominium_charges_monthly"),property_tax_annual:num(f,"property_tax_annual"),condominium_lots:num(f,"condominium_lots"),terrace_m2:num(f,"terrace_m2"),heating:text(f,"heating")||null,exposure:text(f,"exposure")||null,construction_year:num(f,"construction_year"),parking_details:text(f,"parking_details")||null,land_area_m2:num(f,"land_area_m2"),bathrooms:num(f,"bathrooms"),levels:num(f,"levels"),parking_spaces:num(f,"parking_spaces"),property_condition:text(f,"property_condition")||null,kitchen_type:text(f,"kitchen_type")||null,land_is_buildable:f.has("land_is_buildable"),land_is_serviced:f.has("land_is_serviced"),amenities:f.getAll("amenities").map(String),fees_paid_by:text(f,"fees_paid_by")||"Vendeur",contact_name:text(f,"contact_name")||null,contact_phone:text(f,"contact_phone")||null,contact_email:text(f,"contact_email")||null,published_at:status==="published"?new Date().toISOString():null,updated_at:new Date().toISOString()};
 const [property]=await adminRest<{slug:string}[]>(`properties?id=eq.${id}`,{method:"PATCH",headers:{Prefer:"return=representation"},body:JSON.stringify(payload)});if(!property)return NextResponse.json({error:"Bien introuvable"},{status:404});
 const config=getSupabaseAdminConfig();const removals=f.getAll("remove_images").map(String);if(removals.length){const rows=await adminRest<(PropertyImage&{storage_path:string|null})[]>(`property_images?id=in.(${removals.join(",")})&property_id=eq.${id}&select=*`);if(config)for(const row of rows)if(row.storage_path)await fetch(`${config.url}/storage/v1/object/property-images/${row.storage_path}`,{method:"DELETE",headers:{apikey:config.key,Authorization:`Bearer ${config.key}`}});await adminRest(`property_images?id=in.(${removals.join(",")})&property_id=eq.${id}`,{method:"DELETE"});}
 const previous=await adminRest<PropertyImage[]>(`property_images?property_id=eq.${id}&select=*&order=position.desc&limit=1`);let position=(previous[0]?.position??-1)+1;const files=f.getAll("photos").filter((v):v is File=>v instanceof File&&v.size>0);if(config)for(const file of files){const ext=file.type==="image/png"?"png":file.type==="image/webp"?"webp":"jpg";const path=`${id}/${crypto.randomUUID()}.${ext}`;const upload=await fetch(`${config.url}/storage/v1/object/property-images/${path}`,{method:"POST",headers:{apikey:config.key,Authorization:`Bearer ${config.key}`,"Content-Type":file.type},body:await file.arrayBuffer()});if(!upload.ok)throw new Error(await upload.text());await adminRest("property_images",{method:"POST",body:JSON.stringify({property_id:id,storage_path:path,public_url:`${config.url}/storage/v1/object/public/property-images/${path}`,position,is_cover:position===0})});position++;}return NextResponse.json({slug:property.slug});
 }catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Modification impossible"},{status:500});}
}
