import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowLeft, BedDouble, Building2, CalendarDays, Car, ChevronRight, Home, Mail, MapPin, Maximize2, Phone, Ruler, Trees } from "lucide-react";
import { notFound } from "next/navigation";
import { getAdminSession } from "@/lib/admin/auth";
import { getAdminPropertyBySlug, getPublishedProperty } from "@/lib/properties";
import { PropertyGallery } from "./PropertyGallery";
import { absoluteUrl } from "@/lib/site";
import styles from "./property.module.css";

export const dynamic = "force-dynamic";
const money = (value: number) => new Intl.NumberFormat("fr-FR", { style: "currency", currency: "EUR", maximumFractionDigits: 0 }).format(value);
export async function generateMetadata({ params, searchParams }: { params: Promise<{ slug: string }>; searchParams: Promise<{ apercu?: string }> }): Promise<Metadata> { const slug=(await params).slug;const isPreview=(await searchParams).apercu==="1";if(isPreview)return {title:"Aperçu d’un bien immobilier",robots:{index:false,follow:false,noarchive:true}};const property=await getPublishedProperty(slug).catch(()=>null);if(!property)return {title:"Bien immobilier",robots:{index:false,follow:false}};const title=property.seo_title||`${property.title} à ${property.city_name} | Les Jumelles Immo`;const description=property.seo_description||property.short_description||`${property.title} à ${property.city_name}. Découvrez les photos, le prix et les caractéristiques de ce bien immobilier.`;const path=`/biens/${property.slug}`;const images=property.images.map(image=>({url:image.public_url,alt:image.alt_text||property.title}));return {title,description,alternates:{canonical:path},robots:property.seo_noindex?{index:false,follow:false}:{index:true,follow:true},openGraph:{type:"website",locale:"fr_FR",siteName:"Les Jumelles Immo",title,description,url:path,images},twitter:{card:"summary_large_image",title,description,images:images.map(image=>image.url)}}; }

export default async function PropertyPage({ params, searchParams }: { params: Promise<{ slug: string }>; searchParams: Promise<{ apercu?: string }> }) {
  const slug = (await params).slug;
  const isPreview = (await searchParams).apercu === "1";
  let property = await getPublishedProperty(slug).catch(() => null);
  if (!property && isPreview && await getAdminSession()) property = await getAdminPropertyBySlug(slug).catch(() => null);
  if (!property) notFound();
  const images = property.images.length ? property.images : [{ id:"fallback", public_url:"/images/agence-jumelles-immo-hero.webp", alt_text:property.title, position:0, is_cover:true }];
  const facts = [["Type de bien", property.property_type === "house" ? "Maison" : "Appartement"], ["Surface", property.surface_m2 ? `${property.surface_m2} m²` : "—"], ["Étage", property.floor_label || "—"], ["Année", property.construction_year || "—"], ["Exposition", property.exposure || "—"], ["Chauffage", property.heating || "—"], ["Stationnement", property.parking_details || "—"], ["DPE", property.energy_rating || "—"]];
  const propertyJsonLd = { "@context": "https://schema.org", "@graph": [
    { "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Accueil", item: absoluteUrl("/") }, { "@type": "ListItem", position: 2, name: property.city_name, item: absoluteUrl(`/prix-m2/${property.city_name.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "")}`) }, { "@type": "ListItem", position: 3, name: property.title, item: absoluteUrl(`/biens/${property.slug}`) }] },
    { "@type": "Offer", "@id": `${absoluteUrl(`/biens/${property.slug}`)}#offer`, url: absoluteUrl(`/biens/${property.slug}`), price: property.price, priceCurrency: "EUR", availability: "https://schema.org/InStock", seller: { "@id": `${absoluteUrl("/")}#organization` }, itemOffered: { "@type": property.property_type === "house" ? "House" : property.property_type === "apartment" ? "Apartment" : "Residence", name: property.title, description: property.short_description || property.seo_description, image: images.map(image => image.public_url), floorSize: property.surface_m2 ? { "@type": "QuantitativeValue", value: property.surface_m2, unitCode: "MTK" } : undefined, numberOfRooms: property.rooms || undefined, numberOfBedrooms: property.bedrooms || undefined, address: { "@type": "PostalAddress", addressLocality: property.city_name, postalCode: property.postal_code || undefined, streetAddress: property.address || undefined, addressCountry: "FR" } } },
  ] };
  return <main className={styles.page}><script dangerouslySetInnerHTML={{__html:JSON.stringify(propertyJsonLd).replace(/</g,"\\u003c")}} type="application/ld+json"/>{isPreview && property.status !== "published" ? <div className={styles.previewBanner}><strong>Aperçu administrateur</strong><span>Ce bien est en {property.status === "draft" ? "brouillon" : "archive"} et n’est pas encore visible publiquement.</span><Link href={`/admin/biens/${property.id}`}>Modifier le bien</Link></div> : null}<nav className={styles.crumb}><Link href="/"><ArrowLeft size={16}/> Accueil</Link><ChevronRight size={14}/><span>{property.city_name}</span><ChevronRight size={14}/><strong>{property.title}</strong></nav>
    <section className={styles.hero}><PropertyGallery images={images} title={property.title}/>
    <aside className={styles.summary}><p className={styles.eyebrow}>{property.city_name}</p><h1>{property.title}</h1><p>{property.short_description}</p><div className={styles.icons}>{property.surface_m2?<span><Ruler/> {property.surface_m2} m²</span>:null}{property.bedrooms?<span><BedDouble/> {property.bedrooms} chambres</span>:null}{property.floor_label?<span><Building2/> {property.floor_label}</span>:null}{property.terrace_m2?<span><Trees/> Terrasse {property.terrace_m2} m²</span>:null}{property.parking_details?<span><Car/> Parking</span>:null}</div><strong className={styles.price}>{money(property.price)}</strong><small>Honoraires à la charge du {property.fees_paid_by?.toLowerCase() || "vendeur"}</small><a className={styles.primary} href={`mailto:${property.contact_email || "contact@lesjumelles.immo"}?subject=Demande de visite — ${property.title}`}><CalendarDays/> Demander une visite</a><a className={styles.secondary} href={`tel:${property.contact_phone?.replace(/\s/g,"") || ""}`}><Phone/> Contacter l’agence</a></aside></section>
    <div className={styles.body}><div><section className={styles.metrics}>{property.condominium_charges_monthly?<span><Home/><small>Charges</small><strong>{money(property.condominium_charges_monthly)} / mois</strong></span>:null}{property.property_tax_annual?<span><Maximize2/><small>Taxe foncière</small><strong>{money(property.property_tax_annual)} / an</strong></span>:null}{property.condominium_lots?<span><Building2/><small>Copropriété</small><strong>{property.condominium_lots} lots</strong></span>:null}{property.energy_rating?<span><CalendarDays/><small>DPE</small><strong>{property.energy_rating}</strong></span>:null}</section>
    <section className={styles.description}><p className={styles.eyebrow}>Description</p><h2>À propos de ce bien</h2>{property.description?.trim().startsWith("<")?<div className={styles.richDescription} dangerouslySetInnerHTML={{__html:property.description}}/>:property.description?.split("\n").filter(Boolean).map((line,i)=><p key={i}>{line}</p>)}<div className={styles.facts}>{facts.map(([label,value])=><div key={String(label)}><span>{label}</span><strong>{value}</strong></div>)}</div>{property.amenities.length?<div className={styles.amenities}>{property.amenities.map(item=><span key={item}>{item}</span>)}</div>:null}</section></div>
    <aside className={styles.contact}><p className={styles.eyebrow}>Votre contact dédié</p><Image alt="Les Jumelles Immo" height={92} src="/images/laure-severine-jumelles-immo.jpg" width={92}/><h2>{property.contact_name || "Les Jumelles Immo"}</h2><p>À votre écoute pour répondre à toutes vos questions et organiser une visite.</p>{property.contact_phone?<a href={`tel:${property.contact_phone.replace(/\s/g,"")}`}><Phone/> {property.contact_phone}</a>:null}<a href={`mailto:${property.contact_email || "contact@lesjumelles.immo"}`}><Mail/> Envoyer un message</a><div className={styles.location}><MapPin/><div><strong>{property.city_name}</strong><span>{property.neighborhood || property.postal_code}</span></div></div></aside></div>
  </main>;
}
