import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowLeft, BedDouble, Building2, CalendarDays, Car, ChevronRight, Home, Mail, MapPin, Maximize2, Phone, Ruler, Search, Trees } from "lucide-react";
import { notFound } from "next/navigation";
import { getAdminSession } from "@/lib/admin/auth";
import { getAdminPropertyBySlug, getApproximatePropertyLocation, getPublicAmenities, getPublishedProperty, isExclusiveProperty } from "@/lib/properties";
import { PropertyGallery } from "./PropertyGallery";
import { PropertyLocationMap } from "./PropertyLocationMap";
import { PropertyAnalyticsTracker, TrackedPropertyLink } from "./PropertyAnalytics";
import { geocodePropertyAddress } from "@/lib/property-geocoding";
import { absoluteUrl } from "@/lib/site";
import styles from "./property.module.css";

export const dynamic = "force-dynamic";
const money = (value: number) => new Intl.NumberFormat("fr-FR", { style: "currency", currency: "EUR", maximumFractionDigits: 0 }).format(value);
export async function generateMetadata({ params, searchParams }: { params: Promise<{ slug: string }>; searchParams: Promise<{ apercu?: string }> }): Promise<Metadata> { const slug=(await params).slug;const isPreview=(await searchParams).apercu==="1";if(isPreview)return {title:"Aperçu d’un bien immobilier",robots:{index:false,follow:false,noarchive:true}};const property=await getPublishedProperty(slug).catch(()=>null);if(!property)return {title:"Bien immobilier",robots:{index:false,follow:false}};const soldPrefix=property.status==="sold"?"Vendu — ":"";const title=property.seo_title||`${soldPrefix}${property.title} à ${property.city_name} | Les Jumelles Immo`;const description=property.seo_description||(property.status==="sold"?`${property.title} à ${property.city_name}, vendu par Les Jumelles Immo. Vous avez un bien similaire ? Découvrez notre accompagnement vendeur.`:property.short_description||`${property.title} à ${property.city_name}. Découvrez les photos, le prix et les caractéristiques de ce bien immobilier.`);const path=`/biens/${property.slug}`;const images=property.images.map(image=>({url:image.public_url,alt:image.alt_text||property.title}));return {title,description,alternates:{canonical:path},robots:property.seo_noindex?{index:false,follow:false}:{index:true,follow:true},openGraph:{type:"website",locale:"fr_FR",siteName:"Les Jumelles Immo",title,description,url:path,images},twitter:{card:"summary_large_image",title,description,images:images.map(image=>image.url)}}; }

export default async function PropertyPage({ params, searchParams }: { params: Promise<{ slug: string }>; searchParams: Promise<{ apercu?: string }> }) {
  const slug = (await params).slug;
  const isPreview = (await searchParams).apercu === "1";
  let property = await getPublishedProperty(slug).catch(() => null);
  if (!property && isPreview && await getAdminSession()) property = await getAdminPropertyBySlug(slug).catch(() => null);
  if (!property) notFound();
  const isSold = property.status === "sold";
  const isExclusive = isExclusiveProperty(property);
  const publicAmenities = getPublicAmenities(property);
  const geocodedLocation = property.latitude !== null && property.longitude !== null
    ? { latitude: property.latitude, longitude: property.longitude }
    : await geocodePropertyAddress(property.address ?? "", property.postal_code ?? "", property.city_name);
  const approximateLocation = getApproximatePropertyLocation({ ...property, ...geocodedLocation });
  const images = property.images.length ? property.images : [{ id:"fallback", public_url:"/images/agence-jumelles-immo-hero.webp", alt_text:property.title, position:0, is_cover:true }];
  const facts = [["Type de bien", property.property_type === "house" ? "Maison" : "Appartement"], ["Surface", property.surface_m2 ? `${property.surface_m2} m²` : "—"], ["Étage", property.floor_label || "—"], ["Année", property.construction_year || "—"], ["Exposition", property.exposure || "—"], ["Chauffage", property.heating || "—"], ["Stationnement", property.parking_details || "—"], ["DPE", property.energy_rating || "—"]];
  const propertyJsonLd = { "@context": "https://schema.org", "@graph": [
    { "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Accueil", item: absoluteUrl("/") }, { "@type": "ListItem", position: 2, name: property.city_name, item: absoluteUrl(`/prix-m2/${property.city_name.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "")}`) }, { "@type": "ListItem", position: 3, name: property.title, item: absoluteUrl(`/biens/${property.slug}`) }] },
    { "@type": "Offer", "@id": `${absoluteUrl(`/biens/${property.slug}`)}#offer`, url: absoluteUrl(`/biens/${property.slug}`), price: property.price, priceCurrency: "EUR", availability: isSold ? "https://schema.org/SoldOut" : "https://schema.org/InStock", seller: { "@id": `${absoluteUrl("/")}#organization` }, itemOffered: { "@type": property.property_type === "house" ? "House" : property.property_type === "apartment" ? "Apartment" : "Residence", name: property.title, description: property.short_description || property.seo_description, image: images.map(image => image.public_url), floorSize: property.surface_m2 ? { "@type": "QuantitativeValue", value: property.surface_m2, unitCode: "MTK" } : undefined, numberOfRooms: property.rooms || undefined, numberOfBedrooms: property.bedrooms || undefined, address: { "@type": "PostalAddress", addressLocality: property.city_name, postalCode: property.postal_code || undefined, addressCountry: "FR" } } },
  ] };
  return <main className={styles.page}><script dangerouslySetInnerHTML={{__html:JSON.stringify(propertyJsonLd).replace(/</g,"\\u003c")}} type="application/ld+json"/>{isPreview && !["published", "sold"].includes(property.status) ? <div className={styles.previewBanner}><strong>Aperçu administrateur</strong><span>Ce bien est en {property.status === "draft" ? "brouillon" : "archive"} et n’est pas encore visible publiquement.</span><Link href={`/admin/biens/${property.id}`}>Modifier le bien</Link></div> : null}<nav className={styles.crumb}><Link href="/"><ArrowLeft size={16}/> Accueil</Link><ChevronRight size={14}/><span>{property.city_name}</span><ChevronRight size={14}/><strong>{property.title}</strong></nav>
    <PropertyAnalyticsTracker propertyId={property.id}/><section className={styles.hero}><PropertyGallery images={images} isExclusive={isExclusive} isSold={isSold} title={property.title}/>
    <aside className={styles.summary}><p className={styles.eyebrow}>{property.city_name}</p><h1>{property.title}</h1><p>{property.short_description}</p><div className={styles.icons}>{property.surface_m2?<span><Ruler/> {property.surface_m2} m²</span>:null}{property.bedrooms?<span><BedDouble/> {property.bedrooms} chambres</span>:null}{property.floor_label?<span><Building2/> {property.floor_label}</span>:null}{property.terrace_m2?<span><Trees/> Terrasse {property.terrace_m2} m²</span>:null}{property.parking_details?<span><Car/> Parking</span>:null}</div>{isSold?<><strong className={styles.soldTitle}>Vendu par Les Jumelles</strong><small>Ce bien a trouvé acquéreur grâce à notre accompagnement.</small><Link className={styles.primary} href="/recherche"><Search/> Rechercher un bien similaire</Link><TrackedPropertyLink className={styles.secondary} eventType="email_click" href={`mailto:${property.contact_email || "contact@lesjumelles.immo"}?subject=Je souhaite vendre un bien similaire — ${property.title}`} propertyId={property.id}><Mail/> Confier mon bien à l’agence</TrackedPropertyLink></>:<><strong className={styles.price}>{money(property.price)}</strong><small>Honoraires à la charge du {property.fees_paid_by?.toLowerCase() || "vendeur"}</small><TrackedPropertyLink className={styles.primary} eventType="visit_request" href={`mailto:${property.contact_email || "contact@lesjumelles.immo"}?subject=Demande de visite — ${property.title}`} propertyId={property.id}><CalendarDays/> Demander une visite</TrackedPropertyLink><TrackedPropertyLink className={styles.secondary} eventType="phone_click" href={`tel:${property.contact_phone?.replace(/\s/g,"") || ""}`} propertyId={property.id}><Phone/> Contacter l’agence</TrackedPropertyLink></>}</aside></section>
    <div className={styles.body}><div><section className={styles.metrics}>{property.condominium_charges_monthly?<span><Home/><small>Charges</small><strong>{money(property.condominium_charges_monthly)} / mois</strong></span>:null}{property.property_tax_annual?<span><Maximize2/><small>Taxe foncière</small><strong>{money(property.property_tax_annual)} / an</strong></span>:null}{property.condominium_lots?<span><Building2/><small>Copropriété</small><strong>{property.condominium_lots} lots</strong></span>:null}{property.energy_rating?<span><CalendarDays/><small>DPE</small><strong>{property.energy_rating}</strong></span>:null}</section>
    <section className={styles.description}><div className={styles.facts}>{facts.map(([label,value])=><div key={String(label)}><span>{label}</span><strong>{value}</strong></div>)}</div>{publicAmenities.length?<div className={styles.amenities}>{publicAmenities.map(item=><span key={item}>{item}</span>)}</div>:null}<div className={styles.descriptionCopy}><p className={styles.eyebrow}>Description</p><h2>À propos de ce bien</h2>{property.description?.trim().startsWith("<")?<div className={styles.richDescription} dangerouslySetInnerHTML={{__html:property.description}}/>:property.description?.split("\n").filter(Boolean).map((line,i)=><p key={i}>{line}</p>)}</div></section></div>
    <aside className={styles.contact}><p className={styles.eyebrow}>{isSold ? "Votre projet vendeur" : "Votre contact dédié"}</p><Image alt="Les Jumelles Immo" height={92} src="/images/laure-severine-jumelles-immo.jpg" width={92}/><h2>{property.contact_name || "Les Jumelles Immo"}</h2><p>{isSold ? "Vous avez un bien similaire ? Parlons de sa valeur et de la meilleure stratégie pour le vendre." : "À votre écoute pour répondre à toutes vos questions et organiser une visite."}</p>{property.contact_phone?<TrackedPropertyLink eventType="phone_click" href={`tel:${property.contact_phone.replace(/\s/g,"")}`} propertyId={property.id}><Phone/> {property.contact_phone}</TrackedPropertyLink>:null}<TrackedPropertyLink eventType="email_click" href={`mailto:${property.contact_email || "contact@lesjumelles.immo"}?subject=${isSold ? `Projet de vente similaire — ${property.title}` : `Question sur le bien — ${property.title}`}`} propertyId={property.id}><Mail/> {isSold ? "Parler de mon projet" : "Envoyer un message"}</TrackedPropertyLink>{approximateLocation?<div className={styles.locationMap}><PropertyLocationMap accessToken={process.env.NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN??""} center={approximateLocation} radiusMeters={approximateLocation.radiusMeters}/><div className={styles.locationMapCaption}><MapPin/><div><strong>{property.city_name}</strong><span>{property.neighborhood || property.postal_code}</span></div></div></div>:<div className={styles.location}><MapPin/><div><strong>{property.city_name}</strong><span>{property.neighborhood || property.postal_code}</span></div></div>}</aside></div>
  </main>;
}
