"use client";
import { useState } from "react";
import Image from "next/image";
import { GripVertical, LoaderCircle, RotateCcw, Star, Trash2 } from "lucide-react";
import type { Property } from "@/lib/properties";
import styles from "../properties.module.css";
import { PhotoDropzone } from "./PhotoDropzone";
import { RichTextEditor } from "./RichTextEditor";

const options = ["Terrasse","Balcon","Parking","Garage","Ascenseur","Cave","Jardin","Piscine","Vue mer","Climatisation","Cheminée","Accès PMR"];
async function optimize(file: File) { if (!file.type.startsWith("image/") || file.size < 500000) return file; try { const bitmap=await createImageBitmap(file); const ratio=Math.min(1,1800/Math.max(bitmap.width,bitmap.height)); const canvas=document.createElement("canvas"); canvas.width=Math.round(bitmap.width*ratio); canvas.height=Math.round(bitmap.height*ratio); canvas.getContext("2d")?.drawImage(bitmap,0,0,canvas.width,canvas.height); const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,"image/webp",.82)); bitmap.close(); return blob?new File([blob],file.name.replace(/\.[^.]+$/,".webp"),{type:"image/webp"}):file; } catch{return file;} }

export function PropertyForm({ property }: { property?: Property }) {
  const [busy,setBusy]=useState(false); const [message,setMessage]=useState(""); const [photos,setPhotos]=useState<File[]>([]); const [propertyType,setPropertyType]=useState(property?.property_type??"apartment"); const [removedImages,setRemovedImages]=useState<string[]>([]); const [imageOrder,setImageOrder]=useState(property?.images.map(image=>image.id)??[]); const [draggedImage,setDraggedImage]=useState<string|null>(null);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage("Optimisation et envoi…"); const form=new FormData(event.currentTarget); form.delete("photos"); for(const photo of photos) form.append("photos",await optimize(photo)); const response=await fetch(property?`/admin/api/properties/${property.id}`:"/admin/api/properties",{method:property?"PATCH":"POST",body:form}); const result=await response.json(); if(!response.ok){setMessage(result.error||"Enregistrement impossible.");setBusy(false);return;} window.location.href=`/admin/biens?${property?"updated":"created"}=${result.slug}`; }
  const val=(key:keyof Property)=>property?.[key] ?? "";
  const orderedImages=imageOrder.map(id=>property?.images.find(image=>image.id===id)).filter((image):image is NonNullable<typeof image>=>Boolean(image));
  const contactSection=<section><h3>Coordonnées de l’agence</h3><p className={styles.sectionIntro}>Ces informations seront affichées sur la fiche publique pour les demandes de visite.</p><div className={styles.grid}><label>Nom<input defaultValue={property?.contact_name??"Les Jumelles Immo"} name="contact_name"/></label><label>Téléphone<input defaultValue={String(val("contact_phone"))} name="contact_phone"/></label><label>Email<input defaultValue={String(val("contact_email"))} name="contact_email" type="email"/></label><label>Honoraires<select defaultValue={property?.fees_paid_by??"Vendeur"} name="fees_paid_by"><option>Vendeur</option><option>Acquéreur</option></select></label></div></section>;
  return <form className={styles.form} onSubmit={submit}>
    <div className={styles.formHeader}><div><span>{property?"Modification":"Nouvelle annonce"}</span><h2>{property?"Modifier la fiche":"Créer une fiche bien"}</h2></div><select defaultValue={property?.status??"draft"} name="status"><option value="draft">Brouillon</option><option value="published">Publié</option><option value="archived">Archivé</option></select></div>
    {contactSection}
    <section><h3>Informations essentielles</h3><div className={styles.grid}>
      <label className={styles.wide}>Titre<input defaultValue={property?.title} name="title" required /></label><label>Ville<input defaultValue={property?.city_name} name="city_name" required /></label><label>Code postal<input defaultValue={String(val("postal_code"))} name="postal_code" /></label>
      <label>Quartier<input defaultValue={String(val("neighborhood"))} name="neighborhood" /></label><label>Type de bien<select name="property_type" onChange={event=>setPropertyType(event.target.value)} value={propertyType}><option value="apartment">Appartement</option><option value="house">Maison</option><option value="land">Terrain</option><option value="other">Autre</option></select></label>
      <label>Prix (€)<input defaultValue={property?.price} name="price" required type="number" min="0" /></label><label>Surface (m²)<input defaultValue={String(val("surface_m2"))} name="surface_m2" type="number" step="0.1" /></label><label>Pièces<input defaultValue={String(val("rooms"))} name="rooms" type="number" /></label><label>Chambres<input defaultValue={String(val("bedrooms"))} name="bedrooms" type="number" /></label>
      <label>Étage<input defaultValue={String(val("floor_label"))} name="floor_label" /></label><label>Adresse<input defaultValue={String(val("address"))} name="address" /></label><label className={styles.wide}>Accroche<input defaultValue={String(val("short_description"))} name="short_description" /></label><label className={styles.wide}>Description du bien<RichTextEditor initialContent={String(val("description"))} name="description"/></label>
    </div></section>
    <section><h3>Galerie photos</h3><p className={styles.sectionIntro}>Faites glisser les photos pour modifier leur ordre. La première image est toujours la couverture.</p><input name="image_order" type="hidden" value={JSON.stringify(imageOrder.filter(id=>!removedImages.includes(id)))}/>{orderedImages.length?<div className={styles.currentPhotos}>{orderedImages.map((image,index)=>{const removed=removedImages.includes(image.id);return <article data-cover={index===0&&!removed} data-removed={removed} draggable={!removed} key={image.id} onDragStart={()=>setDraggedImage(image.id)} onDragOver={event=>event.preventDefault()} onDrop={()=>{if(!draggedImage||draggedImage===image.id)return;setImageOrder(current=>{const next=current.filter(id=>id!==draggedImage);next.splice(next.indexOf(image.id),0,draggedImage);return next});setDraggedImage(null)}}><div className={styles.photoVisual}><Image alt={image.alt_text??"Photo du bien"} height={95} src={image.public_url} width={150}/>{!removed?<span><GripVertical/> {index===0?<><Star/> Principale</>:`Position ${index+1}`}</span>:null}</div>{removed?<><span>Photo supprimée à l’enregistrement</span><button className={styles.restorePhoto} onClick={()=>setRemovedImages(current=>current.filter(id=>id!==image.id))} type="button"><RotateCcw/> Annuler</button><input name="remove_images" type="hidden" value={image.id}/></>:<div className={styles.photoButtons}>{index>0?<button className={styles.mainPhoto} onClick={()=>setImageOrder(current=>[image.id,...current.filter(id=>id!==image.id)])} type="button"><Star/> Mettre en principale</button>:null}<button className={styles.deletePhoto} onClick={()=>setRemovedImages(current=>[...current,image.id])} type="button"><Trash2/> Supprimer</button></div>}</article>})}</div>:null}<PhotoDropzone files={photos} onChange={setPhotos}/></section>
    <section><h3>Caractéristiques</h3><div className={styles.grid}><label>Terrasse (m²)<input defaultValue={String(val("terrace_m2"))} name="terrace_m2" type="number"/></label><label>Exposition<input defaultValue={String(val("exposure"))} name="exposure"/></label><label>Chauffage<input defaultValue={String(val("heating"))} name="heating"/></label><label>Année<input defaultValue={String(val("construction_year"))} name="construction_year" type="number"/></label><label>Charges / mois<input defaultValue={String(val("condominium_charges_monthly"))} name="condominium_charges_monthly" type="number"/></label><label>Taxe foncière / an<input defaultValue={String(val("property_tax_annual"))} name="property_tax_annual" type="number"/></label><label>Lots<input defaultValue={String(val("condominium_lots"))} name="condominium_lots" type="number"/></label><label>DPE<select defaultValue={property?.energy_rating??""} name="energy_rating"><option value="">Non renseigné</option>{["A","B","C","D","E","F","G"].map(v=><option key={v}>{v}</option>)}</select></label><label className={styles.wide}>Stationnement<input defaultValue={String(val("parking_details"))} name="parking_details"/></label></div><div className={styles.checks}>{options.map(item=><label key={item}><input defaultChecked={property?.amenities.includes(item)} name="amenities" type="checkbox" value={item}/>{item}</label>)}</div></section>
    <section><h3>{propertyType==="house"?"Informations maison":propertyType==="land"?"Informations terrain":propertyType==="apartment"?"Informations appartement":"Informations complémentaires"}</h3><div className={styles.grid}>{propertyType==="house"?<><label>Surface du terrain (m²)<input defaultValue={String(val("land_area_m2"))} name="land_area_m2" type="number"/></label><label>Nombre de niveaux<input defaultValue={String(val("levels"))} name="levels" type="number"/></label><label>Salles d’eau / bains<input defaultValue={String(val("bathrooms"))} name="bathrooms" type="number"/></label><label>Type de cuisine<input defaultValue={String(val("kitchen_type"))} name="kitchen_type"/></label></>:null}{propertyType==="apartment"?<><label>Salles d’eau / bains<input defaultValue={String(val("bathrooms"))} name="bathrooms" type="number"/></label><label>Type de cuisine<input defaultValue={String(val("kitchen_type"))} name="kitchen_type"/></label></>:null}{propertyType==="land"?<><label>Surface du terrain (m²)<input defaultValue={String(val("land_area_m2"))} name="land_area_m2" type="number"/></label><label className={styles.checkLine}><input defaultChecked={property?.land_is_buildable??false} name="land_is_buildable" type="checkbox"/> Constructible</label><label className={styles.checkLine}><input defaultChecked={property?.land_is_serviced??false} name="land_is_serviced" type="checkbox"/> Viabilisé</label></>:null}{propertyType!=="land"?<><label>État du bien<select defaultValue={String(val("property_condition"))} name="property_condition"><option value="">Non renseigné</option><option>Neuf</option><option>Excellent état</option><option>Bon état</option><option>À rafraîchir</option><option>À rénover</option></select></label><label>Places de stationnement<input defaultValue={String(val("parking_spaces"))} name="parking_spaces" type="number"/></label></>:null}</div></section>
    <section><h3>Référencement de l’annonce</h3><p className={styles.sectionIntro}>Personnalisez l’affichage Google. Si ces champs restent vides, le titre et l’accroche de l’annonce seront utilisés.</p><div className={styles.grid}><label className={styles.wide}>Titre SEO — environ 60 caractères<input defaultValue={property?.seo_title??""} maxLength={70} name="seo_title" placeholder={`${property?.title??"Type de bien"} à ${property?.city_name??"Ville"} | Les Jumelles Immo`}/></label><label className={styles.wide}>Méta-description — environ 155 caractères<textarea defaultValue={property?.seo_description??""} maxLength={170} name="seo_description" placeholder="Décrivez le bien, sa localisation et son principal atout." rows={3}/></label><label className={styles.checkLine}><input defaultChecked={property?.seo_noindex??false} name="seo_noindex" type="checkbox"/> Masquer temporairement cette annonce des moteurs de recherche</label></div><div className={styles.seoPreview}><small>Aperçu Google</small><strong>{property?.seo_title||property?.title||"Titre de votre annonce"}</strong><span>immo-rho.vercel.app › biens › {property?.slug||"votre-annonce"}</span><p>{property?.seo_description||property?.short_description||"La description SEO de votre annonce apparaîtra ici."}</p></div></section>
    <div className={styles.actions}><p aria-live="polite">{message}</p><button disabled={busy}>{busy?<LoaderCircle className={styles.spin}/>:null}{property?"Enregistrer les modifications":"Enregistrer le bien"}</button></div>
  </form>;
}
