create table if not exists public.property_analytics_events (
  id bigint generated by default as identity primary key,
  property_id uuid not null references public.properties(id) on delete cascade,
  event_type text not null check (event_type in ('view', 'visit_request', 'phone_click', 'email_click')),
  visitor_hash text not null,
  dedupe_key text not null unique,
  referrer_host text,
  device_type text not null default 'desktop' check (device_type in ('mobile', 'tablet', 'desktop')),
  created_at timestamptz not null default now()
);

create index if not exists property_analytics_property_date_idx
  on public.property_analytics_events (property_id, created_at desc);
create index if not exists property_analytics_property_event_idx
  on public.property_analytics_events (property_id, event_type, created_at desc);

alter table public.property_analytics_events enable row level security;
revoke all on table public.property_analytics_events from anon, authenticated;
grant select, insert, delete on table public.property_analytics_events to service_role;
grant usage, select on sequence public.property_analytics_events_id_seq to service_role;

comment on table public.property_analytics_events is
  'Événements anonymisés des fiches biens. Aucun nom, email ou adresse IP n’est stocké.';
