-- Attribution first-party du parcours public et rattachement des conversions.
-- Les identifiants visiteurs sont haches cote serveur : aucune IP brute n'est stockee.

alter table public.admin_users drop constraint if exists admin_users_role_check;
alter table public.admin_users
  add constraint admin_users_role_check
  check (role in ('admin', 'manager', 'editor', 'agent'));

alter table public.admin_role_permissions drop constraint if exists admin_role_permissions_role_check;
alter table public.admin_role_permissions
  add constraint admin_role_permissions_role_check
  check (role in ('admin', 'manager', 'editor', 'agent'));

insert into public.admin_role_permissions (role, permission)
values
  ('agent', 'buyer_searches:read'),
  ('agent', 'estimations:read'),
  ('agent', 'clients:read')
on conflict (role, permission) do nothing;

create table if not exists public.attribution_links (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  admin_user_id uuid not null references public.admin_users(id) on delete cascade,
  code text not null,
  label text not null default 'Lien principal',
  landing_path text not null default '/',
  utm_source text not null default 'agent',
  utm_medium text not null default 'referral',
  utm_campaign text not null default 'apporteur',
  utm_content text,
  is_active boolean not null default true,
  constraint attribution_links_code_format check (code ~ '^[a-z0-9][a-z0-9-]{2,39}$'),
  constraint attribution_links_landing_path check (landing_path ~ '^/')
);

create unique index if not exists attribution_links_code_unique_idx
  on public.attribution_links (lower(code));
create index if not exists attribution_links_admin_idx
  on public.attribution_links (admin_user_id, created_at desc);

-- Donne immédiatement un lien stable aux comptes déjà présents. Le suffixe
-- issu de l'UUID garantit l'unicité même lorsque deux agents portent le même nom.
insert into public.attribution_links (
  admin_user_id,
  code,
  label,
  landing_path,
  utm_source,
  utm_medium,
  utm_campaign
)
select
  user_row.id,
  coalesce(
    nullif(trim(both '-' from regexp_replace(lower(user_row.full_name), '[^a-z0-9]+', '-', 'g')), ''),
    'agent'
  ) || '-' || left(user_row.id::text, 6),
  'Lien principal',
  '/',
  'agent',
  'referral',
  'apporteur'
from public.admin_users as user_row
where not exists (
  select 1
  from public.attribution_links as existing_link
  where existing_link.admin_user_id = user_row.id
);

drop trigger if exists set_attribution_links_updated_at on public.attribution_links;
create trigger set_attribution_links_updated_at
before update on public.attribution_links
for each row execute function public.set_updated_at();

create table if not exists public.visitor_attributions (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  visitor_hash text not null unique,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  first_source text not null default 'direct',
  first_medium text not null default 'none',
  first_campaign text,
  first_content text,
  first_referrer_host text,
  first_landing_path text not null default '/',
  first_admin_user_id uuid references public.admin_users(id) on delete set null,
  first_link_id uuid references public.attribution_links(id) on delete set null,
  last_source text not null default 'direct',
  last_medium text not null default 'none',
  last_campaign text,
  last_content text,
  last_referrer_host text,
  last_landing_path text not null default '/',
  last_admin_user_id uuid references public.admin_users(id) on delete set null,
  last_link_id uuid references public.attribution_links(id) on delete set null,
  last_path text not null default '/',
  touch_count integer not null default 1 check (touch_count > 0)
);

create index if not exists visitor_attributions_first_admin_idx
  on public.visitor_attributions (first_admin_user_id, first_seen_at desc);
create index if not exists visitor_attributions_last_admin_idx
  on public.visitor_attributions (last_admin_user_id, last_seen_at desc);

drop trigger if exists set_visitor_attributions_updated_at on public.visitor_attributions;
create trigger set_visitor_attributions_updated_at
before update on public.visitor_attributions
for each row execute function public.set_updated_at();

create table if not exists public.attribution_touches (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  visitor_attribution_id uuid not null references public.visitor_attributions(id) on delete cascade,
  path text not null,
  source text not null,
  medium text not null,
  campaign text,
  content text,
  referrer_host text,
  admin_user_id uuid references public.admin_users(id) on delete set null,
  attribution_link_id uuid references public.attribution_links(id) on delete set null,
  is_entry boolean not null default false
);

create index if not exists attribution_touches_visitor_date_idx
  on public.attribution_touches (visitor_attribution_id, created_at desc);
create index if not exists attribution_touches_admin_date_idx
  on public.attribution_touches (admin_user_id, created_at desc);

alter table public.property_estimations
  add column if not exists attribution_visitor_id uuid references public.visitor_attributions(id) on delete set null,
  add column if not exists attributed_admin_user_id uuid references public.admin_users(id) on delete set null,
  add column if not exists assigned_admin_user_id uuid references public.admin_users(id) on delete set null,
  add column if not exists attribution_snapshot jsonb not null default '{}'::jsonb;

alter table public.buyer_searches
  add column if not exists attribution_visitor_id uuid references public.visitor_attributions(id) on delete set null,
  add column if not exists attributed_admin_user_id uuid references public.admin_users(id) on delete set null,
  add column if not exists assigned_admin_user_id uuid references public.admin_users(id) on delete set null,
  add column if not exists attribution_snapshot jsonb not null default '{}'::jsonb;

alter table public.client_accounts
  add column if not exists attribution_visitor_id uuid references public.visitor_attributions(id) on delete set null,
  add column if not exists attributed_admin_user_id uuid references public.admin_users(id) on delete set null,
  add column if not exists assigned_admin_user_id uuid references public.admin_users(id) on delete set null,
  add column if not exists first_attribution jsonb not null default '{}'::jsonb;

alter table public.site_analytics_events
  add column if not exists visitor_attribution_id uuid references public.visitor_attributions(id) on delete set null,
  add column if not exists channel text,
  add column if not exists campaign text,
  add column if not exists attributed_admin_user_id uuid references public.admin_users(id) on delete set null,
  add column if not exists conversion_kind text,
  add column if not exists conversion_id uuid;

create index if not exists property_estimations_attributed_admin_idx on public.property_estimations (attributed_admin_user_id, created_at desc);
create index if not exists buyer_searches_attributed_admin_idx on public.buyer_searches (attributed_admin_user_id, created_at desc);
create index if not exists client_accounts_attributed_admin_idx on public.client_accounts (attributed_admin_user_id, created_at desc);
create index if not exists site_analytics_attribution_idx on public.site_analytics_events (visitor_attribution_id, created_at desc);

alter table public.attribution_links enable row level security;
alter table public.visitor_attributions enable row level security;
alter table public.attribution_touches enable row level security;

revoke all on table public.attribution_links, public.visitor_attributions, public.attribution_touches from anon, authenticated, service_role;
grant select, insert, update, delete on table public.attribution_links, public.visitor_attributions, public.attribution_touches to service_role;
grant usage, select on sequence public.attribution_touches_id_seq to service_role;

comment on table public.visitor_attributions is
  'Attribution first/last touch pseudonymisee. Ne contient ni IP brute ni identite civile.';
