create table if not exists public.site_analytics_events (
  id bigint generated by default as identity primary key,
  event_type text not null check (event_type in ('page_view', 'conversion')),
  audience_type text not null default 'human' check (audience_type in ('human', 'bot', 'suspected')),
  bot_name text,
  path text not null,
  visitor_hash text,
  session_hash text,
  referrer_host text,
  device_type text not null default 'desktop' check (device_type in ('mobile', 'tablet', 'desktop')),
  dedupe_key text not null unique,
  created_at timestamptz not null default now()
);

create index if not exists site_analytics_created_at_idx on public.site_analytics_events (created_at desc);
create index if not exists site_analytics_audience_date_idx on public.site_analytics_events (audience_type, created_at desc);
create index if not exists site_analytics_path_date_idx on public.site_analytics_events (path, created_at desc);

alter table public.site_analytics_events enable row level security;
revoke all on table public.site_analytics_events from anon, authenticated;
grant select, insert, delete on table public.site_analytics_events to service_role;
grant usage, select on sequence public.site_analytics_events_id_seq to service_role;

comment on table public.site_analytics_events is
  'Mesure pseudonymisée de l’audience publique. Aucune adresse IP brute ni identité civile n’est conservée.';
